apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: mysql
  namespace: mysql
  annotations:
    fluxcd.io/ignore: "false"
spec:
  releaseName: mysql
  chart:
    repository: https://kubernetes-charts.storage.googleapis.com/
    name: mysql 
    version: 1.6.2