---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: nginx
  namespace: nginx
spec:
  releaseName: nginx
  chart:
    git: git@github.com:helm/charts
    path: stable/nginx-ingress
    ref: master
